In [1]:
#computing an inverse of the matrix(Transpose)
import numpy as np

matrix = np.array([[1, 0.2, 0.5],[0.2, 1, 0.8],[0.5,0.8,1]])
matrix_transpose = np.transpose(matrix)

print(matrix_transpose)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [2]:
#computing an inverse of the matrix (transpose)
import numpy as np

matrix_transpose = np.array([[1, 0.2,0.5], [0.2, 1,0.8],[0.5,0.8,1]])

inverse_matrix = np.linalg.inv(matrix_transpose)

print(inverse_matrix)

[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


In [1]:
#computing the determinant of the matrix
import numpy as np
matrix = np.array([[1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]])
# Calculate the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

Determinant: 0.2299999999999999


In [1]:
#Decompose the matrix
import numpy as np
matrix = np.array([[1, 0.2, 0.5],[0.2, 1, 0.8],[0.5,0.8,1]])
# Perform matrix decomposition
U, s, V = np.linalg.svd(matrix)
print("U:\n", U)
print("Singular values:", s)
print("V:\n", V)

U:
 [[-0.43721717  0.85359707 -0.28321933]
 [-0.59931898 -0.51133314 -0.61591816]
 [-0.67056536 -0.09955128  0.73514055]]
Singular values: [2.04100779 0.82188052 0.13711169]
V:
 [[-0.43721717 -0.59931898 -0.67056536]
 [ 0.85359707 -0.51133314 -0.09955128]
 [-0.28321933 -0.61591816  0.73514055]]


In [1]:
#Transform the matrix
import numpy as np
matrix = np.array([[1, 0.2, 0.5],[0.2, 1, 0.8],[0.5,0.8,1]])
transposed_matrix = np.transpose(matrix)

# Print the original and transposed matrix
print("Original Matrix:")
print(matrix)
print("\nTransposed Matrix:")
print(transposed_matrix)


Original Matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]

Transposed Matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]
